// @ts-nocheck -- skip type checking
import * as d_docs_12 from "../content/docs/components/buttons/upgrade-button.mdx?collection=docs"
import * as d_docs_11 from "../content/docs/components/buttons/soft-button.mdx?collection=docs"
import * as d_docs_10 from "../content/docs/components/buttons/neumorphism3DButton.mdx?collection=docs"
import * as d_docs_9 from "../content/docs/components/buttons/liquid-button.mdx?collection=docs"
import * as d_docs_8 from "../content/docs/components/buttons/glass-shimmer-button.mdx?collection=docs"
import * as d_docs_7 from "../content/docs/components/cards/premium-profile-card.mdx?collection=docs"
import * as d_docs_6 from "../content/docs/components/cards/particle-card.mdx?collection=docs"
import * as d_docs_5 from "../content/docs/installation/install-tailwind.mdx?collection=docs"
import * as d_docs_4 from "../content/docs/installation/install-nextjs.mdx?collection=docs"
import * as d_docs_3 from "../content/docs/installation/cli.mdx?collection=docs"
import * as d_docs_2 from "../content/docs/installation/add-utilities.mdx?collection=docs"
import * as d_docs_1 from "../content/docs/introduction.mdx?collection=docs"
import * as d_docs_0 from "../content/docs/index.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"index.mdx","fullPath":"content\\docs\\index.mdx"}, data: d_docs_0 }, { info: {"path":"introduction.mdx","fullPath":"content\\docs\\introduction.mdx"}, data: d_docs_1 }, { info: {"path":"installation/add-utilities.mdx","fullPath":"content\\docs\\installation\\add-utilities.mdx"}, data: d_docs_2 }, { info: {"path":"installation/cli.mdx","fullPath":"content\\docs\\installation\\cli.mdx"}, data: d_docs_3 }, { info: {"path":"installation/install-nextjs.mdx","fullPath":"content\\docs\\installation\\install-nextjs.mdx"}, data: d_docs_4 }, { info: {"path":"installation/install-tailwind.mdx","fullPath":"content\\docs\\installation\\install-tailwind.mdx"}, data: d_docs_5 }, { info: {"path":"components/cards/particle-card.mdx","fullPath":"content\\docs\\components\\cards\\particle-card.mdx"}, data: d_docs_6 }, { info: {"path":"components/cards/premium-profile-card.mdx","fullPath":"content\\docs\\components\\cards\\premium-profile-card.mdx"}, data: d_docs_7 }, { info: {"path":"components/buttons/glass-shimmer-button.mdx","fullPath":"content\\docs\\components\\buttons\\glass-shimmer-button.mdx"}, data: d_docs_8 }, { info: {"path":"components/buttons/liquid-button.mdx","fullPath":"content\\docs\\components\\buttons\\liquid-button.mdx"}, data: d_docs_9 }, { info: {"path":"components/buttons/neumorphism3DButton.mdx","fullPath":"content\\docs\\components\\buttons\\neumorphism3DButton.mdx"}, data: d_docs_10 }, { info: {"path":"components/buttons/soft-button.mdx","fullPath":"content\\docs\\components\\buttons\\soft-button.mdx"}, data: d_docs_11 }, { info: {"path":"components/buttons/upgrade-button.mdx","fullPath":"content\\docs\\components\\buttons\\upgrade-button.mdx"}, data: d_docs_12 }]);
export const meta = _runtime.meta<typeof _source.meta>([{"info":{"path":"meta.json","fullPath":"content\\docs\\meta.json"},"data":{"title":"Documentation","description":"RareUI Component Library"}}, {"info":{"path":"installation/meta.json","fullPath":"content\\docs\\installation\\meta.json"},"data":{"title":"Installation","pages":["install-nextjs","install-tailwind","add-utilities","cli"]}}]);