name: 🐛 Bug Report
description: Report a bug or issue with RareUI
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix it faster.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Which component is affected?
      options:
        - Liquid Button
        - Glass Shimmer Button
        - Particle Card
        - Premium Profile Card
        - Soft Button
        - Neumorphism3D Button
        - Upgrade Button
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: RareUI Version
      description: What version of RareUI are you using?
      placeholder: "0.1.5"

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      options:
        - Next.js
        - Create React App
        - Vite
        - Remix
        - Other
    validations:
      required: true

  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        - npm
        - pnpm
        - yarn
        - bun

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide your environment details
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Safari 17]
        - Node version: [e.g., 18.17.0]
        - React version: [e.g., 18.2.0]
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code snippet (optional)
      description: If applicable, add a code snippet to help explain the problem
      render: tsx

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: If applicable, add screenshots to help explain your problem

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all the information requested above
          required: true
