name: 💡 Feature Request
description: Suggest a new component or feature for RareUI
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your idea.

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Tell us your idea!
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature type
      options:
        - New component
        - Enhancement to existing component
        - New utility/helper
        - Documentation improvement
        - CLI improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it solves
      description: What problem does this feature solve? Is your feature request related to a specific issue?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this feature to work?
      placeholder: "I'd like to see a component that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternatives or workarounds?
      placeholder: "I tried using..."

  - type: textarea
    id: examples
    attributes:
      label: Examples or inspiration
      description: Are there any examples or references that inspired this feature?
      placeholder: |
        - Link to similar component
        - Screenshot of desired behavior
        - Code example

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'd be willing to implement this feature myself
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature request is related to RareUI specifically
          required: true
